### ISSUE TITLE
ValueError: setting an array element with a sequence.

### ISSUE THREAD

**Issue by justintiger** [HW140701/VideoTo3dPoseAndBvh#18]
outputs/inputvideo/video.avi --- elapsed time: 7.605630503036082 s
Traceback (most recent call last):
  File "videopose.py", line 332, in <module>
    inference_video('outputs/inputvideo/video.avi', 'alpha_pose')
  File "videopose.py", line 195, in inference_video
    main(args)
  File "videopose.py", line 74, in main
    keypoints = detector_2d(video_name)
  File "/mnt/sdb1/pose_estimation/3D_pose_estimation/VideoTo3dPoseAndBvh/joints_detectors/Alphapose/gene_npz.py", line 63, in generate_kpts
    kpts = np.array(kpts).astype(np.float32)
ValueError: setting an array element with a sequence.

Can u help?

**Comment by opentld** [comment]
change here :)     joints_detectors/Alphapose/gene_npz.py 
The original code would have had a lot more 'None' behind the kpts array
![image](https://user-images.githubusercontent.com/21096515/163112505-00d68ba8-94d6-4c6c-a3f5-4612b777a2c8.png)
